### ISSUE TITLE
Does Not Build on 4.1 using Debian

### ISSUE THREAD

**Issue by AndruePeters** [abobija/idfx#1]
Using Debian under WSL2, but I think the issue is with the script and Espressif versioning.
idfx attempts to find **build/flash_args**, but the valid path on my system is **build/flash_app_args**.  Changing the script to use this different folder allows it to build. 

This is a clean setup following these instructions: https://docs.espressif.com/projects/esp-idf/en/stable/get-started/index.html

**Comment by abobija** [comment]
It seems like that esp-idf on Ubuntu generate **flash_args** and on Debian **flash_app_args**.
Thank you for feedback. I will modify script to work on Debian as well.

**Comment by abobija** [comment]
Hi @AndruePeters

Support for ESP-IDF v4.1 has been added.
`idfx` now use **flash_project_args** (instead of **flash_args**) which is generated in version 4.1 as well as in the latest version 4.3.

Thanks for feedback one more time!

**Comment by AndruePeters** [comment]
Thank you for creating this script. I found it in the thread about WSL2 not
having USB support.
