### ISSUE TITLE
idfx build command (or any other) doesn't work after fullclean

### ISSUE THREAD

**Issue by adokitkat** [abobija/idfx#13]
Hello again, I just found this bug:

```text
> idf.py fullclean

...

> idfx all COM8
Error: Cannot find build/config.env
Make sure to first build the project with next command
                idfx build

> idfx build
Error: Cannot find build/config.env
Make sure to first build the project with next command
                idfx build
```

After doing a fullclean `idfx` commands do not work and it suggests to run `idfx build`, however it doesn't work either - although running the normal `idf.py build` works just fine.

**Comment by abobija** [comment]
Hi @adokitkat
It's fixed. You can update and check.

Thank you again for one more feedback 👍🏼
