### ISSUE TITLE
idf.py menuconfig alias?

### ISSUE THREAD

**Issue by utkarshsethi** [abobija/idfx#16]
Can be handy? as a way to eliminate calling idf.py completely?

**Comment by utkarshsethi** [comment]
same for idf.py set-target?

**Comment by abobija** [comment]
Nice idea. It will be implemented soon.

**Comment by utkarshsethi** [comment]
@abobija have raised pr for this.

**Comment by abobija** [comment]
@utkarshsethi ok, i will review the code in next few days, thanks for contribution

**Comment by abobija** [comment]
Hi @utkarshsethi

I have merge PR #19 and do more stuff than just aliasing 'menuconfig' command. So I have decided to close this issue and your two PRs (#17 and #18) as well.
Thank you anyway for contributions and for great idea.

To see all what is aliased now you can use `idfx help` command.

And one tip:
You can use `idfx all COM6` for building, flashing and monitoring all at once.

Best regards

**Comment by utkarshsethi** [comment]
Yes, but I prefer to use a better tool like Realterm to monitor. Flash to just build and flash and be ready to monitor on Realterm which also has more features.

Flash really should build + flash.
This is a standard feature in every IDE.

And doing it won't cause it to build again if already built as idf.py build stops if there is no change in the files.

**Comment by abobija** [comment]
If I make idfx to prebuild on `flash` that means there is no command for just flashing.
So I have decided to leave `flash` command as it is (just for flashing).
Instead, I have added a new command `bflash` that will build and flash the app at once.

Take an update of `idfx` and you will be able to use `idfx bflash COMx`.

I hope this will help you.
