### ISSUE TITLE
use idfx flash command in wsl2 ubuntu20.04 ,error: Python needs to be installed on the Windows

### ISSUE THREAD

**Issue by LianKaFoHaLi** [abobija/idfx#24]
just as the title describe,But my windows environment have installed python .
![image](https://user-images.githubusercontent.com/50412488/150684668-ee304549-42e9-4970-8c89-5e210eff39e4.png)
![image](https://user-images.githubusercontent.com/50412488/150684684-fc0a43ce-086e-454c-bc49-23f138e98341.png)

**Comment by abobija** [comment]
Python needs to be present on the `PATH` on the Windows.

**Comment by LianKaFoHaLi** [comment]
> 

Thank you for your reply,python path have been added to the **PATH** in my windows.May be there is too many python versions in windows.
