### ISSUE TITLE
Wrong wsl_root if called from mnt partitions

### ISSUE THREAD

**Issue by dedraPL** [abobija/idfx#5]
When you call idfx from /mnt/c/ or other mounted partition wsl_root has wrong path.
For example if i call idfx from /mnt/d/projects/esp32/hello_world then wsl_root  has value D:\projects\esp32\hello_world
so after all monitor is not working, because it tries to call D:\projects\esp32\hello_worl//home/bartek/esp/esp-idf/tools/idf_monitor.py

**Comment by abobija** [comment]
Hi @dedraPL , thank you for feedback.
This issue has been fixed and you can take new version of script.
