### ISSUE TITLE
monitor cannot find elf file

### ISSUE THREAD

**Issue by dedraPL** [abobija/idfx#7]
When entering monitor, there are several red lines telling that xtensa-esp32-elf-addr2line cannot find .elf file. It occurs on both system directory and mnt.

> --- WARNING: GDB cannot open serial ports accessed as COMx
> --- Using \\.\COM3 instead...
> --- idf_monitor on \\.\COM3 115200 ---
> --- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
> ets Jun  8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0030,len:4
> load:0x3fff0034,len:7092
> load:0x40078000,len:13212
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x40078000: [WinError 2] The sy
> stem cannot find the file specified
> load:0x40080400,len:4568
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x40080400: [WinError 2] The sy
> stem cannot find the file specified
> entry 0x400806f4
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x400806f4: [WinError 2] The sy
> stem cannot find the file specified
> I (31) boot: ESP-IDF v4.2-238-g8cd16b60f 2nd stage bootloader
> I (31) boot: compile time 15:21:55
> I (31) boot: chip revision: 1
> I (35) boot_comm: chip revision: 1, min. bootloader chip revision: 0
> I (51) boot.esp32: SPI Speed      : 40MHz
> I (51) boot.esp32: SPI Mode       : DIO
> I (51) boot.esp32: SPI Flash Size : 2MB
> I (56) boot: Enabling RNG early entropy source...
> I (61) boot: Partition Table:
> I (65) boot: ## Label            Usage          Type ST Offset   Length
> I (72) boot:  0 nvs              WiFi data        01 02 00009000 00006000
> I (79) boot:  1 phy_init         RF data          01 01 0000f000 00001000
> I (87) boot:  2 factory          factory app      00 00 00010000 00100000
> I (94) boot: End of partition table
> I (98) boot_comm: chip revision: 1, min. application chip revision: 0
> I (106) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x05b40 ( 23360) map
> I (124) esp_image: segment 1: paddr=0x00015b68 vaddr=0x3ffb0000 size=0x02070 (  8304) load
> I (127) esp_image: segment 2: paddr=0x00017be0 vaddr=0x40080000 size=0x00404 (  1028) load
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x40080000: [WinError 2] The sy
> stem cannot find the file specified
> I (133) esp_image: segment 3: paddr=0x00017fec vaddr=0x40080404 size=0x0802c ( 32812) load
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x40080404: [WinError 2] The sy
> stem cannot find the file specified
> I (156) esp_image: segment 4: paddr=0x00020020 vaddr=0x400d0020 size=0x12fe4 ( 77796) map
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x400d0020: [WinError 2] The sy
> stem cannot find the file specified
> I (186) esp_image: segment 5: paddr=0x0003300c vaddr=0x40088430 size=0x01acc (  6860) load
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x40088430: [WinError 2] The sy
> stem cannot find the file specified
> I (195) boot: Loaded app from partition at offset 0x10000
> I (195) boot: Disabling RNG early entropy source...
> I (195) cpu_start: Pro cpu up.
> I (199) cpu_start: Application information:
> I (204) cpu_start: Project name:     hello-world
> I (209) cpu_start: App version:      1
> I (213) cpu_start: Compile time:     Feb  7 2021 15:21:46
> I (219) cpu_start: ELF file SHA256:  ae19744891928972...
> I (225) cpu_start: ESP-IDF:          v4.2-238-g8cd16b60f
> I (231) cpu_start: Starting app cpu, entry point is 0x400815e4
> xtensa-esp32-elf-addr2line -pfiaC -e d:/projects/esp32/hello_world/build/hello-world.elf 0x400815e4: [WinError 2] The sy
> stem cannot find the file specified
> I (0) cpu_start: App cpu up.
> I (242) heap_init: Initializing. RAM available for dynamic allocation:
> I (249) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
> I (255) heap_init: At 3FFB28B0 len 0002D750 (181 KiB): DRAM
> I (261) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
> I (267) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
> I (274) heap_init: At 40089EFC len 00016104 (88 KiB): IRAM
> I (280) cpu_start: Pro cpu start user code
> I (298) spi_flash: detected chip: generic
> I (299) spi_flash: flash io: dio
> W (299) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the bi
> nary image header.
> I (309) cpu_start: Starting scheduler on PRO CPU.
> I (0) cpu_start: Starting scheduler on APP CPU.

**Comment by abobija** [comment]
Yes, I know about that.
You can consider that as a warning, and not as a error.
So, basically, you can ignore that for now.

But your application works, right? Getting output in the terminal?

**Comment by dedraPL** [comment]
Yes, output appears in the terminal. I'll ignore that warnings then. 
Thank you for your hard work!

**Comment by abobija** [comment]
No problem and thank you for feedbacks.
Cheers!

**Comment by abobija** [comment]
Hi @dedraPL 

I have found the way to disable the showing of red lines in monitor. I have commit the new version of script.
You can update and test.
Anyway if you still got the red lines after the update of `idfx`, please consider to update `esp-idf` to latest version as well.

Thanks one more time for feedback. 👍🏼

**Comment by dedraPL** [comment]
Hi, 
I had to update esp-idf, because updating only idfx didn't fixed this red lines. Thanks!
