### ISSUE TITLE
My Windows cannot find esptool.py but finds esptool.exe

### ISSUE THREAD

**Issue by adokitkat** [abobija/idfx#9]
That's basically it...

 When I change lines with ```esptool.py``` to  ```esptool.exe``` it starts working for me. 
 
 The ```esptool.exe``` is in Windows PATH apparently - in the ```<Python installation folder>/Scripts/```.
 
 EDIT: Also using just ```esptool``` works too.

**Comment by abobija** [comment]
Hi @adokitkat 
Thank you for feedback.
Can you please try on your side to replace `esptool.py` with `python.exe -m esptool` and check if it will work?

**Comment by adokitkat** [comment]
> Can you please try on your side to replace `esptool.py` with `python.exe -m esptool` and check if it will work?

That works too :) 

Also I found another thing that doesn't work properly for me and that's using flash and monitor commands together like ```idfx flash COMx monitor```. It just flashes the binary. However using monitor command alone works.

**Comment by abobija** [comment]
Thank you very much for this feedbacks. I have fix them.

Now you can use `idfx flash COMX monitor`

Btw, for easier use you can use `idfx all COMX` as well. That will build (*alias for `idf.py build`*) if it is not built, flash and monitor, all at once.

Thank you one more time and best regards.

**Comment by adokitkat** [comment]
Thank you too :)
